"""Dias

Revision ID: 08c67920dfbf
Revises: 50016d57bae4
Create Date: 2023-01-18 11:07:39.825985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08c67920dfbf'
down_revision = '50016d57bae4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dias', sa.Column('orden', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'dias', ['orden'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dias', type_='unique')
    op.drop_column('dias', 'orden')
    # ### end Alembic commands ###
