"""Init

Revision ID: 52b4785412cd
Revises: 
Create Date: 2022-12-31 15:13:54.905408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52b4785412cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=30), nullable=True),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.Column('role', sa.Enum('admin', 'distribuidor', name='roletype'), nullable=False),
    sa.Column('status', sa.Enum('activo', 'inactivo', name='userstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('ordenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto', sa.Enum('chives', 'oregano', 'basil', 'tarragon', 'corriander', 'dill', 'marjoram', 'mint', 'baileaf', 'rosemary', 'thyme', 'thai_basil', 'parsley', name='producttype'), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('unidad', sa.Enum('kg', 'lb', name='productmeasurement'), nullable=False),
    sa.Column('status', sa.Enum('sin_modificar', 'modificado', name='productstatus'), server_default='sin_modificar', nullable=False),
    sa.Column('fecha_de_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('creador_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creador_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_ordenes',
    sa.Column('producto', sa.Enum('chives', 'oregano', 'basil', 'tarragon', 'corriander', 'dill', 'marjoram', 'mint', 'baileaf', 'rosemary', 'thyme', 'thai_basil', 'parsley', name='producttype'), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('unidad', sa.Enum('kg', 'lb', name='productmeasurement'), nullable=False),
    sa.Column('status', sa.Enum('sin_modificar', 'modificado', name='productstatus'), server_default='modificado', nullable=False),
    sa.Column('fecha_de_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('modificador_id', sa.Integer(), nullable=False),
    sa.Column('orden_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['modificador_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_ordenes')
    op.drop_table('ordenes')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
