"""cambio en fecha de creacion a modificacion

Revision ID: 7de2b027e344
Revises: c001b4dbd621
Create Date: 2022-12-31 15:32:00.252307

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7de2b027e344'
down_revision = 'c001b4dbd621'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_ordenes', sa.Column('fecha_de_modificacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('log_ordenes', 'fecha_de_creacion')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_ordenes', sa.Column('fecha_de_creacion', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('log_ordenes', 'fecha_de_modificacion')
    # ### end Alembic commands ###
