"""Dias con fecha

Revision ID: b35887daebb9
Revises: 08c67920dfbf
Create Date: 2023-01-18 11:11:53.095014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b35887daebb9'
down_revision = '08c67920dfbf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dias', sa.Column('fecha', sa.Date(), nullable=True))
    op.drop_constraint('dias_orden_key', 'dias', type_='unique')
    op.drop_column('dias', 'orden')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dias', sa.Column('orden', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_unique_constraint('dias_orden_key', 'dias', ['orden'])
    op.drop_column('dias', 'fecha')
    # ### end Alembic commands ###
