"""INIT

Revision ID: b8c8bedcd4ed
Revises: 
Create Date: 2023-01-02 17:10:38.977201

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b8c8bedcd4ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_ordenes', sa.Column('fecha_de_modificacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('log_ordenes', 'fecha_de_creacion')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_ordenes', sa.Column('fecha_de_creacion', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('log_ordenes', 'fecha_de_modificacion')
    # ### end Alembic commands ###
