"""Into to floar para cantidad

Revision ID: c001b4dbd621
Revises: 52b4785412cd
Create Date: 2022-12-31 15:20:41.179811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c001b4dbd621'
down_revision = '52b4785412cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
